services:
  postgres:
    image: 'postgres:16'
    container_name: schoolapi-db
    environment:
      - 'POSTGRES_DB=schoolapi'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: